language: cpp
sudo: false
dist: trusty
os: linux
compiler:
    - g++
addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - boost1.67
      - cppcheck

script:
    - cppcheck --enable=all --platform=unix64 --language=c++ --std=c++11 cpp_algs/cpp_algs.hpp
    - mkdir build && cd build
    - cmake ..
    - make
    - cd ..
    - g++ -std=c++11 tests/main.cpp -o test -I tests/ -L build/ -l cpp_algs -I cpp_algs/
    - ./test --success
    - rm test && rm -rf build