language: cpp
sudo: false
dist: trusty
compiler:
    - g++
addons:
  apt:
    sources:
      - sourceline: 'ppa:mhier/libboost-latest'
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - boost1.67

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - cd ..
    - g++ -std=c++11 tests/main.cpp -o test -I tests/ -L build/ -l cpp_algs -I cpp_algs/
    - ./test --success
    - rm test && rm -rf build