language: cpp
sudo: false
dist: trusty
compiler:
    - g++
os:
    - linux

script:
    - mkdir build && cd build
    - cmake ..
    - make
    - cd ..
    - g++ -std=c++11 tests/main.cpp -o test -I tests/ -L build/ -l cpp_algs -I cpp_algs/
    - ./test --success
    - rm test && rm -rf build